
var PROPERTIES_RE = /\[([^\]]+)\]/;
var PROPERTIES_RE_IGNORE = /\[ignore\]/i;
var PROPERTIES_RE_PADDING = /^\d+$/;
var PROPERTIES_RE_PADDING_CONTAINER_NAME = /(bg|container)/i;
var PROPERTIES_SEP = ':';

// -----------------------------------------------------------

var PROPERTY_TYPE_CENTER = 'center';
var PROPERTY_TYPE_MARGIN = 'margin';
var PROPERTY_TYPE_PADDING = 'padding';
var PROPERTY_TYPE_SIZE = 'size';
var PROPERTY_TYPE_STACK = 'stack';

var PROPERTY_KEY_WIDTH_STATIC = 'width';
var PROPERTY_KEY_WIDTH_ADDITION = 'width-addition';
var PROPERTY_KEY_WIDTH_PERCENTAGE = 'width-percentage';
var PROPERTY_KEY_WIDTH_PERCENTAGE_FULL = 'width-percentage-full';
var PROPERTY_KEY_WIDTH_MIN = 'width-min';
var PROPERTY_KEY_HEIGHT_STATIC = 'height';
var PROPERTY_KEY_HEIGHT_ADDITION = 'height-addition';
var PROPERTY_KEY_HEIGHT_PERCENTAGE = 'height-percentage';
var PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL = 'height-percentage-full';
var PROPERTY_KEY_HEIGHT_MIN = 'height-min';
var PROPERTY_KEY_PADDING_TOP = 'padding-top';
var PROPERTY_KEY_PADDING_RIGHT = 'padding-right';
var PROPERTY_KEY_PADDING_BOTTOM = 'padding-bottom';
var PROPERTY_KEY_PADDING_LEFT = 'padding-left';
var PROPERTY_KEY_MARGIN_TOP = 'margin-top';
var PROPERTY_KEY_MARGIN_RIGHT = 'margin-right';
var PROPERTY_KEY_MARGIN_BOTTOM = 'margin-bottom';
var PROPERTY_KEY_MARGIN_LEFT = 'margin-left';
var PROPERTY_KEY_STACK_HORIZONTALLY_TOP = 'stack-horizontally-top';
var PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE = 'stack-horizontally-middle';
var PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM = 'stack-horizontally-bottom';
var PROPERTY_KEY_STACK_VERTICALLY_LEFT = 'stack-vertically-left';
var PROPERTY_KEY_STACK_VERTICALLY_CENTER = 'stack-vertically-center';
var PROPERTY_KEY_STACK_VERTICALLY_RIGHT = 'stack-vertically-right';
var PROPERTY_KEY_CENTER_HORIZONTALLY = 'center-horizontally';
var PROPERTY_KEY_CENTER_VERTICALLY = 'center-vertically';

var PROPERTY_KEY_PRIORITY = [
    PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE,
    PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM,
    PROPERTY_KEY_STACK_HORIZONTALLY_TOP,
    PROPERTY_KEY_STACK_VERTICALLY_CENTER,
    PROPERTY_KEY_STACK_VERTICALLY_LEFT,
    PROPERTY_KEY_STACK_VERTICALLY_RIGHT,
    PROPERTY_KEY_WIDTH_STATIC,
    PROPERTY_KEY_WIDTH_PERCENTAGE,
    PROPERTY_KEY_WIDTH_PERCENTAGE_FULL,
    PROPERTY_KEY_WIDTH_ADDITION,
    PROPERTY_KEY_WIDTH_MIN,
    PROPERTY_KEY_HEIGHT_STATIC,
    PROPERTY_KEY_HEIGHT_PERCENTAGE,
    PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL,
    PROPERTY_KEY_HEIGHT_ADDITION,
    PROPERTY_KEY_HEIGHT_MIN,
    PROPERTY_KEY_CENTER_HORIZONTALLY,
    PROPERTY_KEY_CENTER_VERTICALLY,
    PROPERTY_KEY_MARGIN_RIGHT,
    PROPERTY_KEY_MARGIN_BOTTOM,
    PROPERTY_KEY_MARGIN_TOP,
    PROPERTY_KEY_MARGIN_LEFT,
    PROPERTY_KEY_PADDING_RIGHT,
    PROPERTY_KEY_PADDING_BOTTOM,
    PROPERTY_KEY_PADDING_TOP,
    PROPERTY_KEY_PADDING_LEFT,
];

// -----------------------------------------------------------

var CLASS_ARTBOARD = 'MSArtboardGroup';
var CLASS_GROUP = 'MSLayerGroup';
var CLASS_SHAPE = 'MSShapeGroup';
var CLASS_SYMBOL_INSTANCE = 'MSSymbolInstance';
var CLASS_SYMBOL_MASTER = 'MSSymbolMaster';
var CLASS_TEXT = 'MSTextLayer';

// -----------------------------------------------------------

global.PROPERTIES_RE = PROPERTIES_RE;
global.PROPERTIES_RE_IGNORE = PROPERTIES_RE_IGNORE;
global.PROPERTIES_RE_PADDING = PROPERTIES_RE_PADDING;
global.PROPERTIES_RE_PADDING_CONTAINER_NAME = PROPERTIES_RE_PADDING_CONTAINER_NAME;
global.PROPERTIES_SEP = PROPERTIES_SEP;
global.PROPERTY_TYPE_CENTER = PROPERTY_TYPE_CENTER;
global.PROPERTY_TYPE_MARGIN = PROPERTY_TYPE_MARGIN;
global.PROPERTY_TYPE_PADDING = PROPERTY_TYPE_PADDING;
global.PROPERTY_TYPE_SIZE = PROPERTY_TYPE_SIZE;
global.PROPERTY_TYPE_STACK = PROPERTY_TYPE_STACK;
global.PROPERTY_KEY_WIDTH_STATIC = PROPERTY_KEY_WIDTH_STATIC;
global.PROPERTY_KEY_WIDTH_ADDITION = PROPERTY_KEY_WIDTH_ADDITION;
global.PROPERTY_KEY_WIDTH_PERCENTAGE = PROPERTY_KEY_WIDTH_PERCENTAGE;
global.PROPERTY_KEY_WIDTH_PERCENTAGE_FULL = PROPERTY_KEY_WIDTH_PERCENTAGE_FULL;
global.PROPERTY_KEY_WIDTH_MIN = PROPERTY_KEY_WIDTH_MIN;
global.PROPERTY_KEY_HEIGHT_STATIC = PROPERTY_KEY_HEIGHT_STATIC;
global.PROPERTY_KEY_HEIGHT_ADDITION = PROPERTY_KEY_HEIGHT_ADDITION;
global.PROPERTY_KEY_HEIGHT_PERCENTAGE = PROPERTY_KEY_HEIGHT_PERCENTAGE;
global.PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL = PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL;
global.PROPERTY_KEY_HEIGHT_MIN = PROPERTY_KEY_HEIGHT_MIN;
global.PROPERTY_KEY_PADDING_TOP = PROPERTY_KEY_PADDING_TOP;
global.PROPERTY_KEY_PADDING_RIGHT = PROPERTY_KEY_PADDING_RIGHT;
global.PROPERTY_KEY_PADDING_BOTTOM = PROPERTY_KEY_PADDING_BOTTOM;
global.PROPERTY_KEY_PADDING_LEFT = PROPERTY_KEY_PADDING_LEFT;
global.PROPERTY_KEY_MARGIN_TOP = PROPERTY_KEY_MARGIN_TOP;
global.PROPERTY_KEY_MARGIN_RIGHT = PROPERTY_KEY_MARGIN_RIGHT;
global.PROPERTY_KEY_MARGIN_BOTTOM = PROPERTY_KEY_MARGIN_BOTTOM;
global.PROPERTY_KEY_MARGIN_LEFT = PROPERTY_KEY_MARGIN_LEFT;
global.PROPERTY_KEY_STACK_HORIZONTALLY_TOP = PROPERTY_KEY_STACK_HORIZONTALLY_TOP;
global.PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE = PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE;
global.PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM = PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM;
global.PROPERTY_KEY_STACK_VERTICALLY_LEFT = PROPERTY_KEY_STACK_VERTICALLY_LEFT;
global.PROPERTY_KEY_STACK_VERTICALLY_CENTER = PROPERTY_KEY_STACK_VERTICALLY_CENTER;
global.PROPERTY_KEY_STACK_VERTICALLY_RIGHT = PROPERTY_KEY_STACK_VERTICALLY_RIGHT;
global.PROPERTY_KEY_CENTER_HORIZONTALLY = PROPERTY_KEY_CENTER_HORIZONTALLY;
global.PROPERTY_KEY_CENTER_VERTICALLY = PROPERTY_KEY_CENTER_VERTICALLY;
global.PROPERTY_KEY_PRIORITY = PROPERTY_KEY_PRIORITY;
global.CLASS_ARTBOARD = CLASS_ARTBOARD;
global.CLASS_GROUP = CLASS_GROUP;
global.CLASS_SHAPE = CLASS_SHAPE;
global.CLASS_SYMBOL_INSTANCE = CLASS_SYMBOL_INSTANCE;
global.CLASS_SYMBOL_MASTER = CLASS_SYMBOL_MASTER;
global.CLASS_TEXT = CLASS_TEXT;
