
const IS_DEBUGGING = print != undefined && log != undefined

const PROPERTIES_RE = new RegExp('\\[([^\\]]+)\\]');
const PROPERTIES_RE_IGNORE = /\[ignore\]/i;
const PROPERTIES_RE_PADDING = /^\d+$/;
const PROPERTIES_RE_PADDING_CONTAINER_NAME = /(bg|container)/i;
const PROPERTIES_SEP = ':';

// -----------------------------------------------------------

const PROPERTY_TYPE_CENTER = 'center';
const PROPERTY_TYPE_MARGIN = 'margin';
const PROPERTY_TYPE_PADDING = 'padding';
const PROPERTY_TYPE_SIZE = 'size';
const PROPERTY_TYPE_STACK = 'stack';

const PROPERTY_KEY_WIDTH_STATIC = 'width';
const PROPERTY_KEY_WIDTH_ADDITION = 'width-addition';
const PROPERTY_KEY_WIDTH_PERCENTAGE = 'width-percentage';
const PROPERTY_KEY_WIDTH_PERCENTAGE_FULL = 'width-percentage-full';
const PROPERTY_KEY_WIDTH_MIN = 'width-min';
const PROPERTY_KEY_HEIGHT_STATIC = 'height';
const PROPERTY_KEY_HEIGHT_ADDITION = 'height-addition';
const PROPERTY_KEY_HEIGHT_PERCENTAGE = 'height-percentage';
const PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL = 'height-percentage-full';
const PROPERTY_KEY_HEIGHT_MIN = 'height-min';
const PROPERTY_KEY_PADDING_TOP = 'padding-top';
const PROPERTY_KEY_PADDING_RIGHT = 'padding-right';
const PROPERTY_KEY_PADDING_BOTTOM = 'padding-bottom';
const PROPERTY_KEY_PADDING_LEFT = 'padding-left';
const PROPERTY_KEY_MARGIN_TOP = 'margin-top';
const PROPERTY_KEY_MARGIN_RIGHT = 'margin-right';
const PROPERTY_KEY_MARGIN_BOTTOM = 'margin-bottom';
const PROPERTY_KEY_MARGIN_LEFT = 'margin-left';
const PROPERTY_KEY_STACK_HORIZONTALLY_TOP = 'stack-horizontally-top';
const PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE = 'stack-horizontally-middle';
const PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM = 'stack-horizontally-bottom';
const PROPERTY_KEY_STACK_VERTICALLY_LEFT = 'stack-vertically-left';
const PROPERTY_KEY_STACK_VERTICALLY_CENTER = 'stack-vertically-center';
const PROPERTY_KEY_STACK_VERTICALLY_RIGHT = 'stack-vertically-right';
const PROPERTY_KEY_CENTER_HORIZONTALLY = 'center-horizontally';
const PROPERTY_KEY_CENTER_VERTICALLY = 'center-vertically';

const PROPERTY_KEY_PRIORITY = [
    PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE,
    PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM,
    PROPERTY_KEY_STACK_HORIZONTALLY_TOP,
    PROPERTY_KEY_STACK_VERTICALLY_CENTER,
    PROPERTY_KEY_STACK_VERTICALLY_LEFT,
    PROPERTY_KEY_STACK_VERTICALLY_RIGHT,
    PROPERTY_KEY_WIDTH_STATIC,
    PROPERTY_KEY_WIDTH_PERCENTAGE,
    PROPERTY_KEY_WIDTH_PERCENTAGE_FULL,
    PROPERTY_KEY_WIDTH_ADDITION,
    PROPERTY_KEY_WIDTH_MIN,
    PROPERTY_KEY_HEIGHT_STATIC,
    PROPERTY_KEY_HEIGHT_PERCENTAGE,
    PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL,
    PROPERTY_KEY_HEIGHT_ADDITION,
    PROPERTY_KEY_HEIGHT_MIN,
    PROPERTY_KEY_CENTER_HORIZONTALLY,
    PROPERTY_KEY_CENTER_VERTICALLY,
    PROPERTY_KEY_MARGIN_RIGHT,
    PROPERTY_KEY_MARGIN_BOTTOM,
    PROPERTY_KEY_MARGIN_TOP,
    PROPERTY_KEY_MARGIN_LEFT,
    PROPERTY_KEY_PADDING_RIGHT,
    PROPERTY_KEY_PADDING_BOTTOM,
    PROPERTY_KEY_PADDING_TOP,
    PROPERTY_KEY_PADDING_LEFT,
];

// -----------------------------------------------------------

const CLASS_ARTBOARD = 'MSArtboardGroup';
const CLASS_GROUP = 'MSLayerGroup';
const CLASS_SHAPE = 'MSShapeGroup';
const CLASS_SYMBOL_INSTANCE = 'MSSymbolInstance';
const CLASS_SYMBOL_MASTER = 'MSSymbolMaster';
const CLASS_TEXT = 'MSTextLayer';

// -----------------------------------------------------------

module.exports = {
    IS_DEBUGGING,
    PROPERTIES_RE,
    PROPERTIES_RE_IGNORE,
    PROPERTIES_RE_PADDING,
    PROPERTIES_RE_PADDING_CONTAINER_NAME,
    PROPERTIES_SEP,
    PROPERTY_TYPE_CENTER,
    PROPERTY_TYPE_MARGIN,
    PROPERTY_TYPE_PADDING,
    PROPERTY_TYPE_SIZE,
    PROPERTY_TYPE_STACK,
    PROPERTY_KEY_WIDTH_STATIC,
    PROPERTY_KEY_WIDTH_ADDITION,
    PROPERTY_KEY_WIDTH_PERCENTAGE,
    PROPERTY_KEY_WIDTH_PERCENTAGE_FULL,
    PROPERTY_KEY_WIDTH_MIN,
    PROPERTY_KEY_HEIGHT_STATIC,
    PROPERTY_KEY_HEIGHT_ADDITION,
    PROPERTY_KEY_HEIGHT_PERCENTAGE,
    PROPERTY_KEY_HEIGHT_PERCENTAGE_FULL,
    PROPERTY_KEY_HEIGHT_MIN,
    PROPERTY_KEY_PADDING_TOP,
    PROPERTY_KEY_PADDING_RIGHT,
    PROPERTY_KEY_PADDING_BOTTOM,
    PROPERTY_KEY_PADDING_LEFT,
    PROPERTY_KEY_MARGIN_TOP,
    PROPERTY_KEY_MARGIN_RIGHT,
    PROPERTY_KEY_MARGIN_BOTTOM,
    PROPERTY_KEY_MARGIN_LEFT,
    PROPERTY_KEY_STACK_HORIZONTALLY_TOP,
    PROPERTY_KEY_STACK_HORIZONTALLY_MIDDLE,
    PROPERTY_KEY_STACK_HORIZONTALLY_BOTTOM,
    PROPERTY_KEY_STACK_VERTICALLY_LEFT,
    PROPERTY_KEY_STACK_VERTICALLY_CENTER,
    PROPERTY_KEY_STACK_VERTICALLY_RIGHT,
    PROPERTY_KEY_CENTER_HORIZONTALLY,
    PROPERTY_KEY_CENTER_VERTICALLY,
    PROPERTY_KEY_PRIORITY,
    CLASS_ARTBOARD,
    CLASS_GROUP,
    CLASS_SHAPE,
    CLASS_SYMBOL_INSTANCE,
    CLASS_SYMBOL_MASTER,
    CLASS_TEXT
};
